name: Publish Docker Image
on:
  push:
    branches:
      - v2.2.0

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Replace branch without `v`
      if: startsWith(github.ref, 'refs/heads/') && github.ref != 'refs/heads/master'
      uses: actions/github-script@v1
      id: version
      with:
        script: |
          return context.payload.ref.replace(/\/?refs\/heads\/v/, '')
        result-encoding: string
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/s390x
        file: docker/Dockerfile
        context: .
        push: true
        tags: |
          tingv/qinglong:${{steps.version.outputs.result}}
